name:                servant-demo
version:             0.1.0.0
synopsis:            Demo servant server project

license:             BSD-3-Clause
license-file:        LICENSE
author:              Soares Chen
maintainer:          soares.chen@maybevoid.com

ghc-options:
  -Wall -O2

dependencies:
  - base ^>=4.12.0.0 && < 5
  - servant == 0.15.*
  - servant-server
  - mtl
  - stm
  - wai
  - text
  - free
  - aeson
  - transformers

default-extensions:
  - GADTs
  - Strict
  - StrictData
  - RankNTypes
  - ExplicitForAll
  - ScopedTypeVariables
  - MultiParamTypeClasses

library:
  source-dirs:  src/lib

  exposed-modules:
    - Acme.App
    - Acme.Model
    - Acme.Route
    - Acme.Effect
    - Acme.Server
    - Acme.Handler

executables:
  demo-server:
    main:          Main.hs
    source-dirs:   src/main
    dependencies:
      - servant-demo
      - warp

tests:
  servant-demo-test:
    main:           Main.hs
    source-dirs:    src/test
    dependencies:
      - servant-demo
      - async
      - tasty
      - QuickCheck
      - tasty-hunit
      - tasty-quickcheck